# Generated by Django 4.2.7 on 2023-11-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
