# Generated by Django 4.2.7 on 2023-12-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fechaDevolucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fechaPrestamo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
