# Generated by Django 4.2.7 on 2023-12-12 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaapp', '0003_alter_usuario_direccion_alter_usuario_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='titulo',
            new_name='libro',
        ),
    ]
