# Generated by Django 4.2.7 on 2023-12-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaapp', '0004_rename_titulo_prestamo_libro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='libro',
            new_name='titulo',
        ),
    ]
