# Generated by Django 4.2.7 on 2023-12-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecaapp', '0005_rename_libro_prestamo_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='titulo',
            new_name='libro',
        ),
    ]
